// THIS FILE IS AUTOGENERATED AND MANAGED BY BARRELBOT. DO NOT EDIT

// for more info: https://github.com/sw-yx/barrelbot
export * from './compat.js'
export * from './index.html'
export * from './main.css'
export * from './main.tsx'